### ISSUE TITLE
Wave effect is not working

### ISSUE THREAD

**Issue by vaibhav93** [noodny/materializecss-amd#2]
dropdown and sideNave are working fine but no wave effects

**Comment by noodny** [comment]
The `Waves` object is exposed on the built module, you need to initialize it when the page is rendered, try something like

``` javascript
define(['materialize'], function(Materialize) {
    Materialize.Waves.displayEffect();
})
```

**Comment by vaibhav93** [comment]
@noodny Thanks. Got that a while ago. Forgot to update here. Thanks
